# Generated by Django 2.1 on 2018-09-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180911_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoty_name',
            new_name='category_name',
        ),
    ]
